version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:22.04-5.9
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.9"

  test:
    image: swift-service-lifecycle:22.04-5.9
    environment:
      - SKIP_SIGNAL_TEST=true
      - FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-service-lifecycle:22.04-5.9
